name: first-workflow
on: push
jobs:
    lint-test-deploy:
	runs-on: ubuntu-latest
    steps:
      - name: lint-step
        run: lint
      - name: test-step
        run: test
      - name: build-step
        run: build
